"use strict";
exports.__esModule = true;
var game_1 = require("../server/game/game");
var g = new game_1.Game();
g.add(0, 0, 'x');
g.render();
g.add(1, 1, 'x');
g.render();
g.add(2, 2, 'x');
g.render();
var g2 = new game_1.Game();
g2.add(2, 0, 'x');
g2.render();
g2.add(1, 1, 'x');
g2.render();
g2.add(0, 2, 'x');
g2.render();
var g3 = new game_1.Game();
g3.add(0, 2, 'o');
g3.render();
g3.add(1, 2, 'o');
g3.render();
g3.add(2, 2, 'o');
g3.render();
var g4 = new game_1.Game(19, 5);
g4.add(2, 2, 'o');
g4.render();
g4.add(3, 2, 'o');
g4.render();
g4.add(4, 2, 'x');
g4.render();
g4.add(5, 2, 'o');
g4.render();
g4.add(6, 2, 'o');
g4.render();
g4.add(4, 2, 'o');
g4.render();
